"""Embed web/ assets into include/WebAssets.h as gzip-compressed byte arrays.

Runs automatically as a PlatformIO pre-build script (see platformio.ini) and can
also be run by hand:  python tools/embed_web.py

Each asset gets a content hash ETag so browsers revalidate with a tiny 304
instead of downloading the page again.
"""
import gzip
import hashlib
import os
import re

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WEB_DIR = os.path.join(PROJECT_DIR, "web")
OUT_FILE = os.path.join(PROJECT_DIR, "include", "WebAssets.h")
MIME = {".html": "text/html", ".css": "text/css", ".js": "application/javascript", ".svg": "image/svg+xml"}


def minify(text):
    # Conservative: drop indentation and blank lines only (keeps JS ASI and <pre> safe enough).
    return "\n".join(line.strip() for line in text.splitlines() if line.strip()) + "\n"


def build():
    parts = [
        "// Generated by tools/embed_web.py from web/. Do not edit.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct WebAsset {",
        "  const char* mime;",
        "  const uint8_t* data;",
        "  size_t length;",
        "  const char* etag;",
        "};",
        "",
    ]
    total_raw = total_gz = 0
    for name in sorted(os.listdir(WEB_DIR)):
        ext = os.path.splitext(name)[1]
        if ext not in MIME:
            continue
        raw = minify(open(os.path.join(WEB_DIR, name), encoding="utf-8").read()).encode("utf-8")
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        ident = "WEB_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper()
        etag = '"' + hashlib.sha1(gz).hexdigest()[:12] + '"'
        body = ",".join(str(b) for b in gz)
        parts.append(f"static const uint8_t {ident}_DATA[] PROGMEM = {{{body}}};")
        parts.append(f'static const WebAsset {ident} = {{"{MIME[ext]}", {ident}_DATA, sizeof({ident}_DATA), "{etag.replace(chr(34), chr(92) + chr(34))}"}};')
        parts.append("")
        total_raw += len(raw)
        total_gz += len(gz)
    content = "\n".join(parts)
    old = open(OUT_FILE, encoding="utf-8").read() if os.path.exists(OUT_FILE) else None
    if old != content:  # avoid needless rebuilds
        with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write(content)
    print(f"embed_web: {total_raw} bytes of web assets -> {total_gz} bytes gzip")


build()
